/**
 * Generated by a build script. Do not modify.
 * Check orginal .jsx file.
 */
/* eslint-disable */

((wp2, Drupal2, DrupalGutenberg2) => {
  const {
    MediaLibrary,
    withNativeDialog,
    withGutenbergDialog
  } = DrupalGutenberg2.Components;
  wp2.hooks.addFilter(
    "editor.MediaUpload",
    "core/edit-post/components/media-upload/replace-media-upload",
    () => Drupal2.isMediaLibraryEnabled() ? withNativeDialog(MediaLibrary) : withGutenbergDialog(MediaLibrary)
  );
})(wp, Drupal, DrupalGutenberg, drupalSettings);
